alert_groups:
- invite_link: https://smp11.simplex.im/g#zPoErCgNgc__YenBLhnQroWim-EZAbq6o2JpmRbTg40
  endpoint_name: clandestineInfraAlerts
  group_name: "alerttest" #set this if the group name configured in simpleX is different from the endpoint name used for alerts
deadmans_switch:
  Midas-btm:
    group: "alerttest" # same groupname as above
    alert_threshold_seconds: 30
    trigger_threshold_seconds: 60
    alert_message: "they ded"
    inheritance_filepath: "/alerterconfig/mysikkritfile.zip"
    inheritance_message: "here's the secret data"
